#!/bin/bash

DIR="$( cd "$( dirname "$0" )" && pwd )"

cd $DIR

mkdir -p .linter-javac/build

javac -cp lib/test/'*':lib/runtime/'*'\
 -sourcepath src/app_jar/java:test/app_jar/java\
 -d .linter-javac/build\
 -Xlint\
 $1
